JaGeo/LobsterPy

lobsterpy/cohp/describe.py
lobsterpy/cohp/test/test_describe.py

This is a fix to save automatic plots correctly. So far, only the last plot was saved.

Fix saving of automatic plots

---

lobsterpy/__init__.py
lobsterpy/cli.py
lobsterpy/test/test_cli.py

This is an implementation so that users can provide their own basis functions that they would like to test. Number of bands will be automatically included in INCAR.

Users can provide their own basis

---

.github/workflows/pylint.yml
docs/conf.py
examples/example_script_NaCl.py
examples/example_script_NaCl_all.py
lobsterpy/cli.py
lobsterpy/cohp/analyze.py
lobsterpy/cohp/describe.py
pylintrc
setup.py

Will enable pylint again with better configuration.

Add pylint

---

requirements.txt
setup.py

Update to latest pymatgen version

latest pymatgen version

---

examples/example_script_NaCl.py
lobsterpy/cohp/analyze.py

Fixes the cation-anion issue discovered in https://github.com/JaGeo/LobsterPy/pull/93. Tests will also be added in https://github.com/JaGeo/LobsterPy/pull/93.

Fix cation anion mode

---

lobsterpy/cli.py

Added two new, shorter aliases (auto-plot, autoplot) for the automatic-plot function.

Update automatic-plot keyword

---

lobsterpy/cli.py

Fix the failing test due to a liniting error for PR #107

run black on cli.py

---

docs/source/atomateauto.rst
docs/source/commandlineinterface.rst
docs/source/installation.rst
docs/source/pythoninterface.rst
examples/example_script_NaCl.py
examples/example_script_NaCl_all.py
lobsterpy/cohp/analyze.py

fixing which_bonds 

---

lobsterpy/cli.py
lobsterpy/test/test_cli.py

- added missing createinputs alias in actions
- Add test to check if it works
Closes #165

fix createinputs alias not working, update test for the same

---

pyproject.toml

Remove redundant ipython from doc dependencies

---

lobsterpy/cohp/analyze.py
lobsterpy/cohp/describe.py
tests/cohp/test_describe.py

Addresses the atomate2 post processing issue
https://github.com/materialsproject/atomate2/issues/681

Fix: text generation error when no bonds are detected at site in cation-anion analysis

---

lobsterpy/cli.py
lobsterpy/cohp/analyze.py
tests/cli/test_cli.py

Closes #252 
1. Remove redunant orbplot arg and use orbitalresolved arg

remove redundant orbplot arg and fix a typo

---

lobsterpy/cohp/describe.py

Closes #260 by skipping to display all plots but instead saving them to a file when more than 20 inequivalent ions are found in the structure.

fix automatic plotting for large structures

---

lobsterpy/cli.py

This adds plotting support for multi-center cobi files.

Add preliminary support multicobi

---

docs/tutorial/commandlineinterface.rst

Closes #319 , #318 
Hi @JaGeo , I have now fixed the cli tutorial which were outdated and got overlooked somehow. Could be merged

fix outdated cli tutorial code snippets

---

docs/tutorial/commandlineinterface.rst
src/lobsterpy/cli.py
src/lobsterpy/plotting/layout_dicts.py
tests/cli/test_cli.py

Fix unexpected "DOSCAR.LSO.lobster" exception in cli 

---

paper/paper.md

Update the referred path of lobsterenv.py in pymatgen source code.

Fix the path of lobsterenv.py.

---

.pre-commit-config.yaml
pyproject.toml
tests/cli/test_cli.py
tests/cohp/test_analyze.py
tests/conftest.py
tests/featurize/test_batch.py
tests/featurize/test_core.py
tests/featurize/test_utils.py
tests/plotting/test_plotting.py
tests/structuregraph/test_graph.py

1. Remove redundant flake8 as we already use ruff
2. Run autoupdate pre-commit hooks

Ci updates

---

src/lobsterpy/plotting/__init__.py
tests/plotting/test_plotting.py

Add option to color icoxxlist plots based on atom pair interactions

Enhance icoxxlist plotter

---

codecov.yml
pyproject.toml
tests/cli/test_cli.py

Fix codecov failure

---

src/lobsterpy/cli.py
src/lobsterpy/featurize/core.py
src/lobsterpy/featurize/utils.py

Fix optional dependencies related errors

---

.github/workflows/python-publish.yml
MANIFEST.in
pyproject.toml

1. Exclude wanted test, examples, paper and docs directories from src distribution on pypi

Fix bloated src distribution on pypi
